<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.sbforge</groupId>
        <artifactId>sbforge-parent</artifactId>
        <version>25</version>
        <relativePath />
    </parent>

    <groupId>dk.kb.alma</groupId>
    <artifactId>alma-client</artifactId>
    <version>0.45-SNAPSHOT</version>
    <packaging>jar</packaging>


    <scm>
        <url>https://github.com/kb-dk/alma-client</url>
        <connection>scm:git:git@github.com:kb-dk/alma-client.git</connection>
        <developerConnection>scm:git:git@github.com:kb-dk/alma-client.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <licenses>
        <!--SBForge stuff should have a license-->
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <properties>
        <build.time>${maven.build.timestamp}</build.time>
        <maven.build.timestamp.format>yyyy-MM-dd HH:mm</maven.build.timestamp.format>
        <!-- Run 'mvn package -DallTests' to run all tests, including slow ones
             Annotate tests with '@Tag("slow")' or '@Tag("fast")' -->
        <!-- Specify java version here, to support forbiddenapis plugin -->
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <!-- Replace the line below with  -->
        <api.check.phase>none</api.check.phase>
        <!--       to disable forbidden APIs check -->
        <!--      <api.check.phase>process-classes</api.check.phase>-->

        <license.name>Apache License, Version 2.0</license.name>
        <license.url>https://www.apache.org/licenses/LICENSE-2.0.txt</license.url>
        <description.short>KB Digitisation on Demand</description.short>
        <cxf.version>4.1.4</cxf.version>

        <kb-util.version>2.0.1</kb-util.version>
        <marc4j.version>2.9.2</marc4j.version>
        <guava.version>33.5.0-jre</guava.version>
        <slf4j-api.version>2.0.17</slf4j-api.version>
        <junit.version>6.0.1</junit.version>
        <junit-jupiter-engine.version>${junit.version}</junit-jupiter-engine.version>
        <hamcrest.version>3.0</hamcrest.version>
        <logback-classic.version>1.5.22</logback-classic.version>
        <mockito-core.version>5.21.0</mockito-core.version>
        <maven-javadoc-plugin.version>3.12.0</maven-javadoc-plugin.version>
        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
        <error_prone_core>2.46.0</error_prone_core>
        <maven-jar-plugin.version>3.5.0</maven-jar-plugin.version>
        <license-maven-plugin.version>2.7.1</license-maven-plugin.version>
        <jakarta.xml.bind-api.version>4.0.4</jakarta.xml.bind-api.version>
        <jaxb-runtime.version>4.0.6</jaxb-runtime.version>
        <jaxb-maven-plugin.version>4.0.12</jaxb-maven-plugin.version>
        <angus-activation.version>2.0.3</angus-activation.version>
        <jackson.version>3.0.3</jackson.version>
        <jackson-datatype-jsr310.version>3.0.0-rc2</jackson-datatype-jsr310.version>
        <jackson-annotations.version>3.0-rc2</jackson-annotations.version>
        <jaxb-maven-plugin.generateDirectory>target/generated-sources/</jaxb-maven-plugin.generateDirectory>
    </properties>

    <dependencies>
        <dependency>
            <groupId>dk.kb.util</groupId>
            <artifactId>kb-util</artifactId>
            <version>${kb-util.version}</version>
        </dependency>
        <dependency>
            <groupId>org.marc4j</groupId>
            <artifactId>marc4j</artifactId>
            <version>${marc4j.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-rs-client</artifactId>
            <version>${cxf.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>${jakarta.xml.bind-api.version}</version>
        </dependency>
        <dependency>
            <groupId>tools.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson-datatype-jsr310.version}</version>
        </dependency>
        <dependency>
            <groupId>tools.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>tools.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-xml-provider</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>tools.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito-core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
            <version>${junit-jupiter-engine.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <version>${hamcrest.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback-classic.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>${jaxb-runtime.version}</version>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.angus</groupId>
                <artifactId>angus-activation</artifactId>
                <version>${angus-activation.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-core</artifactId>
                <version>${cxf.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-rt-frontend-jaxrs</artifactId>
                <version>${cxf.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson-annotations.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.21.0</version>
            </dependency>
            <dependency>
                <groupId>tools.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>3.0.0-rc2</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.19.2</version>
            </dependency>
            <dependency>
                <groupId>tools.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>3.0.0-rc2</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.module</groupId>
                <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
                <version>2.20.0</version>
            </dependency>
            <dependency>
                <groupId>jakarta.activation</groupId>
                <artifactId>jakarta.activation-api</artifactId>
                <version>2.1.4</version>
            </dependency>
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>4.0.4</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>2.5</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                <artifactId>jackson-jakarta-rs-base</artifactId>
                <version>2.21.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>
        <resources>
            <resource>
                <directory>target/generated-resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>${license-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>download-licenses</id>
                        <goals>
                            <goal>download-licenses</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <licensesOutputDirectory>
                                ${project.build.directory}/generated-resources/META-INF/dependencies-licenses
                            </licensesOutputDirectory>
                            <excludedScopes>test</excludedScopes>
                            <licensesConfigFile>
                                ${project.build.directory}/generated-resources/META-INF/dependencies-licenses-config.xml
                            </licensesConfigFile>
                            <licensesOutputFile>
                                ${project.build.directory}/generated-resources/META-INF/dependencies-licenses.xml
                            </licensesOutputFile>
                            <licensesErrorsFile>
                                ${project.build.directory}/generated-resources/META-INF/dependencies-licenses-errors.xml
                            </licensesErrorsFile>
                            <includeTransitiveDependencies>true</includeTransitiveDependencies>
                            <organizeLicensesByDependencies>true</organizeLicensesByDependencies>
                            <cleanLicensesOutputDirectory>true</cleanLicensesOutputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven-javadoc-plugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>javadoc</goal>
                        </goals>
                        <configuration>
                            <doclint>none</doclint>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.errorprone</groupId>
                            <artifactId>error_prone_core</artifactId>
                            <version>${error_prone_core}</version>
                        </path>
<!--                        TODO this is very old - Should we remove it? -->
                        <path>
                            <groupId>com.google.guava</groupId>
                            <artifactId>guava-beta-checker</artifactId>
                            <version>1.0</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <compilerArgs>
                                <arg>-XDcompilePolicy=simple</arg>
                                <!-- Remove -XepDisableAllChecks to keep all checks enabled -->
                                <arg>-Xplugin:ErrorProne -XepDisableAllChecks -Xep:BetaApi:ERROR</arg>
                            </compilerArgs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <!-- Disable Beta Checker for tests
                                 NOTE: in this specific case, we could just NOT enable Error Prone at all -->
                            <compilerArgs>
                                <arg>-XDcompilePolicy=simple</arg>
                                <!-- Remove -XepDisableAllChecks to keep all checks enabled -->
                                <arg>-Xplugin:ErrorProne -XepDisableAllChecks -Xep:BetaApi:OFF</arg>
                            </compilerArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.jvnet.jaxb</groupId>
                <artifactId>jaxb-maven-plugin</artifactId>
                <version>${jaxb-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>xjc_alma_sru</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <generatePackage>dk.kb.alma.gen.sru</generatePackage>


                            <schemaExcludes>
                                <exclude>\.txt</exclude>
                                <exclude>\.xjb</exclude>
                            </schemaExcludes>
                            <schemaDirectory>src/main/resources/alma_sru/</schemaDirectory>
                            <removeOldOutput>false</removeOldOutput>
                            <bindingDirectory>${basedir}/src/main/resources/</bindingDirectory>

                        </configuration>
                    </execution>
                </executions>
            </plugin>


            <plugin>
                <groupId>com.evolvedbinary.maven.jvnet</groupId>
                <artifactId>jaxb2-maven-plugin</artifactId>
                <version>${jaxb2-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>rest_portfolios</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>

                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_portfolios.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.portfolios</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-rest_portfolios/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-user_resource_sharing_request</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_user_resource_sharing_requests.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.user_resource_sharing_request</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-user_resource_sharing_request/
                            </generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-partners</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_partners.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.partners</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-partners/
                            </generateDirectory>
                        </configuration>
                    </execution>


                    <execution>
                        <id>web_service_result</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/web_service_result.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <!--These schemas clashes with the other schemas so they need to be located in a different package-->
                            <generatePackage>dk.kb.alma.gen.web_service_result</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-web_service_result/
                            </generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>rest_bibs</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_bibs.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <!--These schemas clashes with the other schemas so they need to be located in a different package-->
                            <generatePackage>dk.kb.alma.gen.bibs</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-bibs/</generateDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>rest_code_table</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_code_table.xsd
                                    </url>
                                </schema>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_code_tables.xsd
                                    </url>
                                </schema>

                            </schemas>
                            <!--These schemas clashes with the other schemas so they need to be located in a different package-->
                            <generatePackage>dk.kb.alma.gen.code_table</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-code_table/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>rest_items</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_items.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <!--These schemas clashes with the other schemas so they need to be located in a different package-->
                            <generatePackage>dk.kb.alma.gen.items</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-items/</generateDirectory>
                        </configuration>
                    </execution>


                    <execution>
                        <id>rest_users</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemaDirectory>src/main/schemas/</schemaDirectory>
                            <schemaIncludes>
                                <include>rest_users.xsd</include>
                                <include>rest_user.xsd</include>
                                <include>rest_researcher.xsd</include>
                            </schemaIncludes>
                            <!--These schemas clashes with the other schemas so they need to be located in a different package-->
                            <generatePackage>dk.kb.alma.gen.users</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-users/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>rest_fees</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_fees.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <!--These schemas clashes with the other schemas so they need to be located in a different package-->
                            <generatePackage>dk.kb.alma.gen.fees</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-fees/</generateDirectory>
                        </configuration>
                    </execution>


                    <execution>
                        <id>rest_libraries</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_libraries.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.libraries</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-libraries/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest_general</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_general.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.general</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-rest_general/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-requested_resources</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_requested_resources.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.requested_resources</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-requested_resources/
                            </generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-user_requests</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_user_requests.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <!--These schemas clashes with the other schemas so they need to be located in a different package-->
                            <generatePackage>dk.kb.alma.gen.user_requests</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-user_requests/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-locations</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_locations.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.locations</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-locations/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-holdings</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_holdings.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.holdings</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-holdings/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-holding</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_holding.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.holding</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-holding/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-analytics</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_analyt_report.xsd
                                    </url>
                                </schema>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_analyt_paths.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.analytics</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-analytics/</generateDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>webhook</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <schemas>
                                <schema>
                                    <fileset>
                                        <directory>src/main/schemas/webhook</directory>
                                        <excludes>
                                            <exclude>rest_bib.xsd</exclude>
                                            <exclude>rest_fee.xsd</exclude>
                                            <exclude>rest_group_settings.xsd</exclude>
                                            <exclude>rest_holding.xsd</exclude>
                                            <exclude>rest_item.xsd</exclude>
                                            <exclude>rest_item_loan.xsd</exclude>
                                            <exclude>rest_job_instance.xsd</exclude>
                                            <exclude>rest_linking_parameters.xsd</exclude>
                                            <exclude>rest_notes.xsd</exclude>
                                            <exclude>rest_network_numbers.xsd</exclude>
                                            <exclude>rest_portfolio.xsd</exclude>
                                            <exclude>rest_representation.xsd</exclude>
                                            <exclude>rest_rs_request_details.xsd</exclude>
                                            <exclude>rest_user_request.xsd</exclude>
                                            <exclude>rest_user_resource_sharing_request.xsd</exclude>
                                        </excludes>
                                    </fileset>
                                </schema>
                            </schemas>
                            <generateDirectory>${generated}webhook</generateDirectory>
                            <generatePackage>dk.kb.alma.gen.webhooks</generatePackage>
                        </configuration>
                    </execution>
                    <execution>
                        <id>alma-rest-item-loans</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_item_loans.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.item.loans</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-item-loans/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-electronic</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemaDirectory>src/main/schemas/electronic</schemaDirectory>
                            <generatePackage>dk.kb.alma.gen.item.electronic</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-electronic/</generateDirectory>
                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-vendors</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_vendors.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.vendor</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-vendors/</generateDirectory>

                        </configuration>
                    </execution>

                    <execution>
                        <id>alma-rest-purchase_requests</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <schemaLanguage>XMLSCHEMA</schemaLanguage>
                            <schemas>
                                <schema>
                                    <url>
                                        https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_purchase_requests.xsd
                                    </url>
                                </schema>
                            </schemas>
                            <generatePackage>dk.kb.alma.gen.purchase_requests</generatePackage>
                            <generateDirectory>${jaxb-maven-plugin.generateDirectory}jaxb-alma-purchase_requests/
                            </generateDirectory>

                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>add-test-resource</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>conf</directory>
                                    <excludes>
                                        <exclude>**/conf/logback.xml</exclude>
                                    </excludes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


        </plugins>


    </build>
</project>
